/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import canteenmanagementsystem.*;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Selva
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        //Receiptname.setText("Receipt For \n"+Login.cur_user);
        Payableamt.setText(String.valueOf(Orderpage.grandTotal));
        Orderno.setText(String.valueOf(OrderInfo.order_id));
        //Balance.setText(String.valueOf(CustomerInfo.ub.get(Login.cur_user).getBal_amount()));
        Orderbox.setText(Orderpage.order_details);
        
        ButtonGroup b = new ButtonGroup();
        b.add(card);
        b.add(cash);
        b.add(wallet);
        
        //add(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Receiptname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Payableamt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Orderno = new javax.swing.JLabel();
        Paybtn = new javax.swing.JButton();
        cash = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();
        wallet = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Orderbox = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Insertcomponents = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 121, 151));

        Receiptname.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Receiptname.setForeground(new java.awt.Color(255, 255, 255));
        Receiptname.setText("Receipt For");
        Receiptname.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                ReceiptnameComponentHidden(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Wallet balance :");

        Balance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Balance.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Receiptname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Receiptname, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Balance))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 540));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setText("Choose a payment mode");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 210, 40));

        Payableamt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(Payableamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 50, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Order no :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        Orderno.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        getContentPane().add(Orderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 30, 20));

        Paybtn.setText("Pay");
        getContentPane().add(Paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 80, 30));

        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        getContentPane().add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 70, 40));

        card.setText("Credit Card");
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 90, 40));

        wallet.setText("Wallet");
        getContentPane().add(wallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 70, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Order Details :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Orderbox.setBackground(new java.awt.Color(242, 242, 242));
        Orderbox.setColumns(20);
        Orderbox.setRows(5);
        jScrollPane1.setViewportView(Orderbox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 140, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setText("Amount to be paid :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 30));

        javax.swing.GroupLayout InsertcomponentsLayout = new javax.swing.GroupLayout(Insertcomponents);
        Insertcomponents.setLayout(InsertcomponentsLayout);
        InsertcomponentsLayout.setHorizontalGroup(
            InsertcomponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        InsertcomponentsLayout.setVerticalGroup(
            InsertcomponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(Insertcomponents, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 330, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReceiptnameComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ReceiptnameComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceiptnameComponentHidden

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
        Paybtn.setText("Proceed");
    }//GEN-LAST:event_cashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance;
    private javax.swing.JPanel Insertcomponents;
    private javax.swing.JTextArea Orderbox;
    private javax.swing.JLabel Orderno;
    private javax.swing.JLabel Payableamt;
    private javax.swing.JButton Paybtn;
    private javax.swing.JLabel Receiptname;
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton cash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton wallet;
    // End of variables declaration//GEN-END:variables
}
