/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import canteenmanagementsystem.CustomerInfo;
import javax.swing.JDialog;

/**
 *
 * @author Ragul S
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        setBounds(0,100,0,0);
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void Validate()
    {
        CustomerInfo ci;
        try{
            String username = Cus_username.getText();
            String password = Cus_password.getText();
            String cpassword = Cus_conpassword.getText();
            String email = Cus_email.getText();
            
            if(username.equals("") || password.equals("") || cpassword.equals("") || email.equals(""))
                throw new NullPointerException();
            
            if(password.equals(cpassword)==false)
            {
                //JOptionPane.showMessageDialog(null,"Password doesn't match");
                final JOptionPane pane = new JOptionPane("Password doesn't match");
                final JDialog d = pane.createDialog((JFrame)null, "Registration Error");
                d.setLocation(250,350);
                d.setVisible(true);
            }
            
            else if(email.matches("[a-zA-Z][a-zA-Z0-9_]*@gmail.com")==false)
            {
             //   JOptionPane.showMessageDialog(null,"Email incorrect");
                final JOptionPane pane = new JOptionPane("Email incorrect");
                final JDialog d = pane.createDialog((JFrame)null, "Registration Error");
                d.setLocation(250,350);
                d.setVisible(true);
            }
            else
            {
                ci = new CustomerInfo(username,password,email,100);
                CustomerInfo.cus_array.add(ci);
                //JOptionPane.showMessageDialog(null,"Registered Successfully");
                final JOptionPane pane = new JOptionPane(username+" registered successfully");
                final JDialog d = pane.createDialog((JFrame)null, "Registration");
                d.setLocation(250,350);
                d.setVisible(true);
                setVisible(false);
                new Login().setVisible(true);
            }
        }
        catch(NullPointerException e)
        {
            //JOptionPane.showMessageDialog(null,"Please Enter all fields");
            final JOptionPane pane = new JOptionPane("Please enter all fields");
                final JDialog d = pane.createDialog((JFrame)null, "Registration Error");
                d.setLocation(250,350);
                d.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cus_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cus_login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cus_register = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Cus_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cus_password = new javax.swing.JPasswordField();
        Cus_conpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 632));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        Cus_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cus_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cus_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(Cus_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 240, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Already have an account?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        Cus_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cus_login.setText("Login");
        Cus_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cus_loginActionPerformed(evt);
            }
        });
        getContentPane().add(Cus_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Canteen Management System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 126, -1));

        Cus_register.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cus_register.setText("Register");
        Cus_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cus_registerActionPerformed(evt);
            }
        });
        getContentPane().add(Cus_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 80, 30));
        getContentPane().add(Cus_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 243, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setText("Register");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, 30));
        getContentPane().add(Cus_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 240, 30));
        getContentPane().add(Cus_conpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cus_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cus_loginActionPerformed

        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_Cus_loginActionPerformed

    private void Cus_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cus_usernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Cus_usernameActionPerformed

    private void Cus_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cus_registerActionPerformed
        Validate();
    }//GEN-LAST:event_Cus_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cus_conpassword;
    private javax.swing.JTextField Cus_email;
    private javax.swing.JButton Cus_login;
    private javax.swing.JPasswordField Cus_password;
    private javax.swing.JButton Cus_register;
    private javax.swing.JTextField Cus_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
