/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import static Model.Login.op;
import static Model.Orderpage.un;
import canteenmanagementsystem.CustomerInfo;
import canteenmanagementsystem.ItemInfo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ragul S
 */
public class SearchItems extends javax.swing.JFrame {

    /**
     * Creates new form UpdateItems
     */
    public SearchItems() {
        initComponents();
        setBounds(820,200,710,450);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        /*DefaultTableModel dtm = (DefaultTableModel) Edittable.getModel();
        dtm.setRowCount(0);
        
        for(ItemInfo it: ItemInfo.item_array){
                dtm.addRow(new Object[]{
                it.getName(),it.getPrice(),it.getAvailable_quantity()
            });
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Searchitemtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edittable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Searchitemtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 240, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Item Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 39));

        SearchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, -1));

        Edittable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price", "Quanity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Edittable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdittableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Edittable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 360, 340));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clear.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/small-page-background.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 20, 270, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String name = Searchitemtxt.getText();
        int flag = 0;
        //JOptionPane.showMessageDialog(null,name+" Not Found !"+ItemInfo.item_array.size());
        DefaultTableModel dtm = (DefaultTableModel) Edittable.getModel();
        dtm.setRowCount(0);
        
        for(ItemInfo it: ItemInfo.item_array){
            if(it.getName().equals(name)){
                dtm.addRow(new Object[]{
                it.getName(),it.getPrice(),it.getAvailable_quantity()
            });
                flag = 1;
            }
        }
        
        if(flag == 0){
            
            /*for(ItemInfo it: ItemInfo.item_array){
                    dtm.addRow(new Object[]{
                    it.getName(),it.getPrice(),it.getAvailable_quantity()
                });
            }*/
            JOptionPane.showMessageDialog(null,name+" Not Found !");
            Searchitemtxt.setText("");
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void EdittableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdittableMouseClicked
        
        int index = Edittable.getSelectedRow();
        TableModel model = Edittable.getModel();
        String name = model.getValueAt(index, 0).toString();
        String price = model.getValueAt(index, 1).toString();
        String quantity = model.getValueAt(index, 2).toString();

        int flag=0;
        String[] options = { "Edit", "Delete", "Cancel" };
        int x = JOptionPane.showOptionDialog(null, "Edit or Delete?", "Select an option",  
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, null);
        /*int a = JOptionPane.showConfirmDialog(null, "Do you want to edit " + name+" ","Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a == 0){
            new UpdateDetails(ItemInfo.item_array,name,price,quantity).setVisible(true);
            flag = 1;
        }

        else
            JOptionPane.showMessageDialog(null,name+" Not Found !"+ItemInfo.item_array.size());*/
        if(x==0)
        {
            new UpdateDetails(ItemInfo.item_array,name,price,quantity).setVisible(true);
            flag = 1;
            Searchitemtxt.setText("");
        }
        
        else if(x==1)
        {
            //ItemInfo i = new ItemInfo(name,Double.parseDouble(price),quantity);
            int a = JOptionPane.showConfirmDialog(null, "Do you want to delete " + name+" ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
            if(a == 0){
            
                for(int i=0;i<ItemInfo.item_array.size();i++)
                {
                    if(ItemInfo.item_array.get(i).getName().equals(name))
                        ItemInfo.item_array.remove(i);
                }
                
                for(int i=0;i<CustomerInfo.order.size();i++)
                {
                    if(CustomerInfo.order.get(i).getName().equals(name))
                        CustomerInfo.order.remove(i);
                }
                
                DefaultTableModel dtm = (DefaultTableModel) Edittable.getModel();
                dtm.setRowCount(0);
        
                op.setVisible(false);
        Login.op = new Orderpage(un);
        op.setVisible(true);
                /*for(ItemInfo it: ItemInfo.item_array){
                    dtm.addRow(new Object[]{
                        it.getName(),it.getPrice(),it.getAvailable_quantity()
                    });
                }
                Searchitemtxt.setText("");*/
            }
        }
        
        if(flag==1)
        setVisible(false);
    }//GEN-LAST:event_EdittableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Searchitemtxt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Edittable;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField Searchitemtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
